name: CI/CD Docker to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el repo
    - uses: actions/checkout@v3

    # 2️⃣ Configurar AWS
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3️⃣ Login a ECR
    - uses: aws-actions/amazon-ecr-login@v1

    # 4️⃣ Build Docker
    - run: docker build -t app-ecs:latest .

    # 5️⃣ Tag Docker
    - run: docker tag app-ecs:latest 919649536077.dkr.ecr.us-east-1.amazonaws.com/app-ecs:latest

    # 6️⃣ Push Docker
    - run: docker push 919649536077.dkr.ecr.us-east-1.amazonaws.com/app-ecs:latest

    # 7️⃣ Deploy ECS
    - run: aws ecs update-service --cluster cluster-app-ecs --service app-ecs-service --force-new-deployment
